//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_postgres.CODE.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_postgres.CODE.Localization.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action List.
        /// </summary>
        internal static string Action_list {
            get {
                return ResourceManager.GetString("Action_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add another source.
        /// </summary>
        internal static string Add_another_source {
            get {
                return ResourceManager.GetString("Add_another_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add author:.
        /// </summary>
        internal static string Add_author {
            get {
                return ResourceManager.GetString("Add_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add city.
        /// </summary>
        internal static string Add_city {
            get {
                return ResourceManager.GetString("Add_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add format.
        /// </summary>
        internal static string Add_format {
            get {
                return ResourceManager.GetString("Add_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add genre.
        /// </summary>
        internal static string Add_genre {
            get {
                return ResourceManager.GetString("Add_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add language.
        /// </summary>
        internal static string Add_language {
            get {
                return ResourceManager.GetString("Add_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add mark.
        /// </summary>
        internal static string Add_mark {
            get {
                return ResourceManager.GetString("Add_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add person.
        /// </summary>
        internal static string Add_person {
            get {
                return ResourceManager.GetString("Add_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add storage location.
        /// </summary>
        internal static string Add_place {
            get {
                return ResourceManager.GetString("Add_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add publishing house.
        /// </summary>
        internal static string Add_pubhouse {
            get {
                return ResourceManager.GetString("Add_pubhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add book series.
        /// </summary>
        internal static string Add_series {
            get {
                return ResourceManager.GetString("Add_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Another.
        /// </summary>
        internal static string Another {
            get {
                return ResourceManager.GetString("Another", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Another source already exists.
        /// </summary>
        internal static string Another_source_already_exists {
            get {
                return ResourceManager.GetString("Another_source_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of other sources of recommendations.
        /// </summary>
        internal static string another_source_list {
            get {
                return ResourceManager.GetString("another_source_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Appellation {
            get {
                return ResourceManager.GetString("Appellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Art.
        /// </summary>
        internal static string Art {
            get {
                return ResourceManager.GetString("Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of arts.
        /// </summary>
        internal static string Art_list {
            get {
                return ResourceManager.GetString("Art_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arts by language.
        /// </summary>
        internal static string Arts_by_language {
            get {
                return ResourceManager.GetString("Arts_by_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author alredy exists.
        /// </summary>
        internal static string Author_alredy_exists {
            get {
                return ResourceManager.GetString("Author_alredy_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author(s).
        /// </summary>
        internal static string Author_s {
            get {
                return ResourceManager.GetString("Author_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authors.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of authors.
        /// </summary>
        internal static string Authors_list {
            get {
                return ResourceManager.GetString("Authors_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authors recommend authors.
        /// </summary>
        internal static string Authors_recommend_authors {
            get {
                return ResourceManager.GetString("Authors_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authors recommend books.
        /// </summary>
        internal static string Authors_recommend_books {
            get {
                return ResourceManager.GetString("Authors_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Book.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Books.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of books.
        /// </summary>
        internal static string Books_list {
            get {
                return ResourceManager.GetString("Books_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of books that were taken from me.
        /// </summary>
        internal static string Books_list_taken_by_others {
            get {
                return ResourceManager.GetString("Books_list_taken_by_others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Books recommend authors.
        /// </summary>
        internal static string Books_recommend_authors {
            get {
                return ResourceManager.GetString("Books_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Books recommend books.
        /// </summary>
        internal static string Books_recommend_books {
            get {
                return ResourceManager.GetString("Books_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à from anothers.
        /// </summary>
        internal static string caption_from_anothers {
            get {
                return ResourceManager.GetString("caption_from_anothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à from authors.
        /// </summary>
        internal static string caption_from_authors {
            get {
                return ResourceManager.GetString("caption_from_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à from books.
        /// </summary>
        internal static string caption_from_books {
            get {
                return ResourceManager.GetString("caption_from_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of cities.
        /// </summary>
        internal static string Cities_list {
            get {
                return ResourceManager.GetString("Cities_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à City already exists.
        /// </summary>
        internal static string City_already_exists {
            get {
                return ResourceManager.GetString("City_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection established.
        /// </summary>
        internal static string Connection_established {
            get {
                return ResourceManager.GetString("Connection_established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit another source.
        /// </summary>
        internal static string Edit_another_source {
            get {
                return ResourceManager.GetString("Edit_another_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit author name.
        /// </summary>
        internal static string Edit_author_name {
            get {
                return ResourceManager.GetString("Edit_author_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit city.
        /// </summary>
        internal static string Edit_city {
            get {
                return ResourceManager.GetString("Edit_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit format.
        /// </summary>
        internal static string Edit_format {
            get {
                return ResourceManager.GetString("Edit_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit genre.
        /// </summary>
        internal static string Edit_genre {
            get {
                return ResourceManager.GetString("Edit_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit language.
        /// </summary>
        internal static string Edit_language {
            get {
                return ResourceManager.GetString("Edit_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit mark.
        /// </summary>
        internal static string Edit_mark {
            get {
                return ResourceManager.GetString("Edit_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit person.
        /// </summary>
        internal static string Edit_person {
            get {
                return ResourceManager.GetString("Edit_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit name of storage location:.
        /// </summary>
        internal static string Edit_place {
            get {
                return ResourceManager.GetString("Edit_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit publishing house.
        /// </summary>
        internal static string Edit_pubhouse {
            get {
                return ResourceManager.GetString("Edit_pubhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit book series.
        /// </summary>
        internal static string Edit_series {
            get {
                return ResourceManager.GetString("Edit_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EN_ini.sql.
        /// </summary>
        internal static string Filename_Init_Script {
            get {
                return ResourceManager.GetString("Filename_Init_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format already exists.
        /// </summary>
        internal static string Format_already_exists {
            get {
                return ResourceManager.GetString("Format_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of reading formats.
        /// </summary>
        internal static string Formats_list {
            get {
                return ResourceManager.GetString("Formats_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Genre.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Genre already exists.
        /// </summary>
        internal static string Genre_already_exists {
            get {
                return ResourceManager.GetString("Genre_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of genres.
        /// </summary>
        internal static string Genres_list {
            get {
                return ResourceManager.GetString("Genres_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Book ID.
        /// </summary>
        internal static string ID_book_short_text {
            get {
                return ResourceManager.GetString("ID_book_short_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The connection to the database server has been established, but the database was not found. It is recommended to create a new database or restore from a backup..
        /// </summary>
        internal static string Info_Connect_OK_DB_not_found {
            get {
                return ResourceManager.GetString("Info_Connect_OK_DB_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database is corrupted.
        ///It is recommended to create a new database or restore from a backup..
        /// </summary>
        internal static string Info_DB_corrupted {
            get {
                return ResourceManager.GetString("Info_DB_corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The connection to the database server has not been established..
        /// </summary>
        internal static string Info_DB_No_Connection {
            get {
                return ResourceManager.GetString("Info_DB_No_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database was not found.
        ///It is recommended to create a new database or restore from a backup..
        /// </summary>
        internal static string Info_DB_not_found {
            get {
                return ResourceManager.GetString("Info_DB_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language already exists.
        /// </summary>
        internal static string Language_already_exists {
            get {
                return ResourceManager.GetString("Language_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication language.
        /// </summary>
        internal static string Language_pub {
            get {
                return ResourceManager.GetString("Language_pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of languages.
        /// </summary>
        internal static string Languages_list {
            get {
                return ResourceManager.GetString("Languages_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Original langue.
        /// </summary>
        internal static string Langue_original {
            get {
                return ResourceManager.GetString("Langue_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mark.
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mark already exists.
        /// </summary>
        internal static string Mark_already_exists {
            get {
                return ResourceManager.GetString("Mark_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of marks.
        /// </summary>
        internal static string Marks_list {
            get {
                return ResourceManager.GetString("Marks_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New city name:.
        /// </summary>
        internal static string New_appellation {
            get {
                return ResourceManager.GetString("New_appellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New format.
        /// </summary>
        internal static string New_format {
            get {
                return ResourceManager.GetString("New_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New name:.
        /// </summary>
        internal static string New_name {
            get {
                return ResourceManager.GetString("New_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notice.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Others recommend authors.
        /// </summary>
        internal static string Others_recommend_authors {
            get {
                return ResourceManager.GetString("Others_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Others recommend books.
        /// </summary>
        internal static string Others_recommend_books {
            get {
                return ResourceManager.GetString("Others_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pages.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The password is correct.
        /// </summary>
        internal static string Password_Correct {
            get {
                return ResourceManager.GetString("Password_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Person.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Person already exists.
        /// </summary>
        internal static string Person_already_exists {
            get {
                return ResourceManager.GetString("Person_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name:.
        /// </summary>
        internal static string Person_short_name {
            get {
                return ResourceManager.GetString("Person_short_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of people.
        /// </summary>
        internal static string Persons_list {
            get {
                return ResourceManager.GetString("Persons_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Storage location: already exists.
        /// </summary>
        internal static string Place_already_exists {
            get {
                return ResourceManager.GetString("Place_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of storage location:.
        /// </summary>
        internal static string Place_name {
            get {
                return ResourceManager.GetString("Place_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Placement.
        /// </summary>
        internal static string Placement {
            get {
                return ResourceManager.GetString("Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Placements list.
        /// </summary>
        internal static string Placements_list {
            get {
                return ResourceManager.GetString("Placements_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publishing house.
        /// </summary>
        internal static string Pubhouse {
            get {
                return ResourceManager.GetString("Pubhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publishing house already exists.
        /// </summary>
        internal static string Pubhouse_already_exists {
            get {
                return ResourceManager.GetString("Pubhouse_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of publishing house:.
        /// </summary>
        internal static string Pubhouse_name {
            get {
                return ResourceManager.GetString("Pubhouse_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of publishing houses.
        /// </summary>
        internal static string Pubhouses_list {
            get {
                return ResourceManager.GetString("Pubhouses_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication year.
        /// </summary>
        internal static string Publication_year {
            get {
                return ResourceManager.GetString("Publication_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Have read.
        /// </summary>
        internal static string Read_list {
            get {
                return ResourceManager.GetString("Read_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recommendation.
        /// </summary>
        internal static string Recommendation {
            get {
                return ResourceManager.GetString("Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recomm. type.
        /// </summary>
        internal static string Recommendation_type {
            get {
                return ResourceManager.GetString("Recommendation_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of recommendations.
        /// </summary>
        internal static string Recommendations_list {
            get {
                return ResourceManager.GetString("Recommendations_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Series.
        /// </summary>
        internal static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Series already exist.
        /// </summary>
        internal static string Series_already_exist {
            get {
                return ResourceManager.GetString("Series_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of series.
        /// </summary>
        internal static string Series_list {
            get {
                return ResourceManager.GetString("Series_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Simple_proper_name {
            get {
                return ResourceManager.GetString("Simple_proper_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source type.
        /// </summary>
        internal static string Source_type {
            get {
                return ResourceManager.GetString("Source_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Storage.
        /// </summary>
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of storage locations.
        /// </summary>
        internal static string Storages_list {
            get {
                return ResourceManager.GetString("Storages_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value cannot be empty.
        /// </summary>
        internal static string Value_cannot_be__empty {
            get {
                return ResourceManager.GetString("Value_cannot_be_ empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure to permanently delete the database?.
        /// </summary>
        internal static string Warning_BD_Deleting {
            get {
                return ResourceManager.GetString("Warning_BD_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Where are the books.
        /// </summary>
        internal static string Where_books {
            get {
                return ResourceManager.GetString("Where_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Who has my books.
        /// </summary>
        internal static string Who_has_my_books {
            get {
                return ResourceManager.GetString("Who_has_my_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Year of writing.
        /// </summary>
        internal static string Writing_year {
            get {
                return ResourceManager.GetString("Writing_year", resourceCulture);
            }
        }
    }
}
