//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_postgres.CODE.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_postgres.CODE.Localization.FR", typeof(FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une autre source de recommandation.
        /// </summary>
        internal static string Add_another_source {
            get {
                return ResourceManager.GetString("Add_another_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter nouveau autheur :.
        /// </summary>
        internal static string Add_author {
            get {
                return ResourceManager.GetString("Add_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un format.
        /// </summary>
        internal static string Add_format {
            get {
                return ResourceManager.GetString("Add_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un genre.
        /// </summary>
        internal static string Add_genre {
            get {
                return ResourceManager.GetString("Add_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une langue.
        /// </summary>
        internal static string Add_language {
            get {
                return ResourceManager.GetString("Add_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une note.
        /// </summary>
        internal static string Add_mark {
            get {
                return ResourceManager.GetString("Add_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une personne.
        /// </summary>
        internal static string Add_person {
            get {
                return ResourceManager.GetString("Add_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un emplacement de stockage.
        /// </summary>
        internal static string Add_place {
            get {
                return ResourceManager.GetString("Add_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une maison d&apos;édition.
        /// </summary>
        internal static string Add_pubhouse {
            get {
                return ResourceManager.GetString("Add_pubhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une série de livres.
        /// </summary>
        internal static string Add_series {
            get {
                return ResourceManager.GetString("Add_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de la ville.
        /// </summary>
        internal static string Appellation {
            get {
                return ResourceManager.GetString("Appellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteur.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;auteur déjà existe .
        /// </summary>
        internal static string Author_alredy_exists {
            get {
                return ResourceManager.GetString("Author_alredy_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteurs.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les auteurs recommandent des auteurs.
        /// </summary>
        internal static string Authors_recommend_authors {
            get {
                return ResourceManager.GetString("Authors_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les auteurs recommandent des livres.
        /// </summary>
        internal static string Authors_recommend_books {
            get {
                return ResourceManager.GetString("Authors_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Livres.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les livres recommandent des auteurs.
        /// </summary>
        internal static string Books_recommend_authors {
            get {
                return ResourceManager.GetString("Books_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les livres recommandent des livres.
        /// </summary>
        internal static string Books_recommend_books {
            get {
                return ResourceManager.GetString("Books_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autres.
        /// </summary>
        internal static string caption_from_anothers {
            get {
                return ResourceManager.GetString("caption_from_anothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Des auteurs.
        /// </summary>
        internal static string caption_from_authors {
            get {
                return ResourceManager.GetString("caption_from_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Des livres.
        /// </summary>
        internal static string caption_from_books {
            get {
                return ResourceManager.GetString("caption_from_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier une autre source de recommandation.
        /// </summary>
        internal static string Edit_another_source {
            get {
                return ResourceManager.GetString("Edit_another_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier le nom de l&apos;auteur.
        /// </summary>
        internal static string Edit_author_name {
            get {
                return ResourceManager.GetString("Edit_author_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier le nom de la ville.
        /// </summary>
        internal static string Edit_city {
            get {
                return ResourceManager.GetString("Edit_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier le format.
        /// </summary>
        internal static string Edit_format {
            get {
                return ResourceManager.GetString("Edit_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier le genre.
        /// </summary>
        internal static string Edit_genre {
            get {
                return ResourceManager.GetString("Edit_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier la langue.
        /// </summary>
        internal static string Edit_language {
            get {
                return ResourceManager.GetString("Edit_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier la note.
        /// </summary>
        internal static string Edit_mark {
            get {
                return ResourceManager.GetString("Edit_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier la personne.
        /// </summary>
        internal static string Edit_person {
            get {
                return ResourceManager.GetString("Edit_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier le nom de l&apos;emplacement.
        /// </summary>
        internal static string Edit_place {
            get {
                return ResourceManager.GetString("Edit_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier la maison d&apos;édition.
        /// </summary>
        internal static string Edit_pubhouse {
            get {
                return ResourceManager.GetString("Edit_pubhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier la série.
        /// </summary>
        internal static string Edit_series {
            get {
                return ResourceManager.GetString("Edit_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format déjà existe .
        /// </summary>
        internal static string Format_already_exists {
            get {
                return ResourceManager.GetString("Format_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le genre déjà existe .
        /// </summary>
        internal static string Genre_already_exists {
            get {
                return ResourceManager.GetString("Genre_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La langue déjà existe .
        /// </summary>
        internal static string Language_already_exists {
            get {
                return ResourceManager.GetString("Language_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La note déjà existe.
        /// </summary>
        internal static string Mark_already_exists {
            get {
                return ResourceManager.GetString("Mark_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau nom de la ville.
        /// </summary>
        internal static string New_appellation {
            get {
                return ResourceManager.GetString("New_appellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau format :.
        /// </summary>
        internal static string New_format {
            get {
                return ResourceManager.GetString("New_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau nom:.
        /// </summary>
        internal static string New_name {
            get {
                return ResourceManager.GetString("New_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les auteurs recommandent des auteurs.
        /// </summary>
        internal static string Others_recommend_authors {
            get {
                return ResourceManager.GetString("Others_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les auteurs recommandent des livres.
        /// </summary>
        internal static string Others_recommend_books {
            get {
                return ResourceManager.GetString("Others_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personne.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La personne déjà existe.
        /// </summary>
        internal static string Person_already_exists {
            get {
                return ResourceManager.GetString("Person_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom, prénom :.
        /// </summary>
        internal static string Person_short_name {
            get {
                return ResourceManager.GetString("Person_short_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;emplacement de stockage déjà existe .
        /// </summary>
        internal static string Place_already_exists {
            get {
                return ResourceManager.GetString("Place_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du lieu de stockage :.
        /// </summary>
        internal static string Place_name {
            get {
                return ResourceManager.GetString("Place_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La maison d&apos;édition déjà existe .
        /// </summary>
        internal static string Pubhouse_already_exists {
            get {
                return ResourceManager.GetString("Pubhouse_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La série déjà existe .
        /// </summary>
        internal static string Series_already_exist {
            get {
                return ResourceManager.GetString("Series_already_exist", resourceCulture);
            }
        }
    }
}
