//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_postgres.CODE.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RU() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_postgres.CODE.Localization.RU", typeof(RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Действие.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список действий.
        /// </summary>
        internal static string Action_list {
            get {
                return ResourceManager.GetString("Action_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить другой источник рекомендации.
        /// </summary>
        internal static string Add_another_source {
            get {
                return ResourceManager.GetString("Add_another_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить автора:.
        /// </summary>
        internal static string Add_author {
            get {
                return ResourceManager.GetString("Add_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить город.
        /// </summary>
        internal static string Add_city {
            get {
                return ResourceManager.GetString("Add_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить формат.
        /// </summary>
        internal static string Add_format {
            get {
                return ResourceManager.GetString("Add_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить жанр.
        /// </summary>
        internal static string Add_genre {
            get {
                return ResourceManager.GetString("Add_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить язык.
        /// </summary>
        internal static string Add_language {
            get {
                return ResourceManager.GetString("Add_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить оценку.
        /// </summary>
        internal static string Add_mark {
            get {
                return ResourceManager.GetString("Add_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить лицо.
        /// </summary>
        internal static string Add_person {
            get {
                return ResourceManager.GetString("Add_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить место хранения.
        /// </summary>
        internal static string Add_place {
            get {
                return ResourceManager.GetString("Add_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить издательство.
        /// </summary>
        internal static string Add_pubhouse {
            get {
                return ResourceManager.GetString("Add_pubhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить серию книг.
        /// </summary>
        internal static string Add_series {
            get {
                return ResourceManager.GetString("Add_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Другое.
        /// </summary>
        internal static string Another {
            get {
                return ResourceManager.GetString("Another", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Источник уже существует.
        /// </summary>
        internal static string Another_source_already_exists {
            get {
                return ResourceManager.GetString("Another_source_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список иных источников рекомендаций.
        /// </summary>
        internal static string another_source_list {
            get {
                return ResourceManager.GetString("another_source_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Название.
        /// </summary>
        internal static string Appellation {
            get {
                return ResourceManager.GetString("Appellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Произведение.
        /// </summary>
        internal static string Art {
            get {
                return ResourceManager.GetString("Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список произведений.
        /// </summary>
        internal static string Art_list {
            get {
                return ResourceManager.GetString("Art_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Произведения по языкам.
        /// </summary>
        internal static string Arts_by_language {
            get {
                return ResourceManager.GetString("Arts_by_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Автор.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Автор уже существует.
        /// </summary>
        internal static string Author_alredy_exists {
            get {
                return ResourceManager.GetString("Author_alredy_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Автор(ы).
        /// </summary>
        internal static string Author_s {
            get {
                return ResourceManager.GetString("Author_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Авторы.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список авторов.
        /// </summary>
        internal static string Authors_list {
            get {
                return ResourceManager.GetString("Authors_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Авторы рекомендуют авторов.
        /// </summary>
        internal static string Authors_recommend_authors {
            get {
                return ResourceManager.GetString("Authors_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Авторы рекомендуют книги.
        /// </summary>
        internal static string Authors_recommend_books {
            get {
                return ResourceManager.GetString("Authors_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Книга.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Книги.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список книг.
        /// </summary>
        internal static string Books_list {
            get {
                return ResourceManager.GetString("Books_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список книг, которые у меня взяли.
        /// </summary>
        internal static string Books_list_taken_by_others {
            get {
                return ResourceManager.GetString("Books_list_taken_by_others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Книги рекомендуют авторов.
        /// </summary>
        internal static string Books_recommend_authors {
            get {
                return ResourceManager.GetString("Books_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Книги рекомендуют книги.
        /// </summary>
        internal static string Books_recommend_books {
            get {
                return ResourceManager.GetString("Books_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Другое.
        /// </summary>
        internal static string caption_from_anothers {
            get {
                return ResourceManager.GetString("caption_from_anothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à От авторов.
        /// </summary>
        internal static string caption_from_authors {
            get {
                return ResourceManager.GetString("caption_from_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Из книг.
        /// </summary>
        internal static string caption_from_books {
            get {
                return ResourceManager.GetString("caption_from_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список городов.
        /// </summary>
        internal static string Cities_list {
            get {
                return ResourceManager.GetString("Cities_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Город.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Город уже существует.
        /// </summary>
        internal static string City_already_exists {
            get {
                return ResourceManager.GetString("City_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Шифр.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Комментарий.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Подключение установлено.
        /// </summary>
        internal static string Connection_established {
            get {
                return ResourceManager.GetString("Connection_established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Дата.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить иной источник рекомендации.
        /// </summary>
        internal static string Edit_another_source {
            get {
                return ResourceManager.GetString("Edit_another_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить имя автора.
        /// </summary>
        internal static string Edit_author_name {
            get {
                return ResourceManager.GetString("Edit_author_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить город.
        /// </summary>
        internal static string Edit_city {
            get {
                return ResourceManager.GetString("Edit_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить формат.
        /// </summary>
        internal static string Edit_format {
            get {
                return ResourceManager.GetString("Edit_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить жанр.
        /// </summary>
        internal static string Edit_genre {
            get {
                return ResourceManager.GetString("Edit_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить язык.
        /// </summary>
        internal static string Edit_language {
            get {
                return ResourceManager.GetString("Edit_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить оценку.
        /// </summary>
        internal static string Edit_mark {
            get {
                return ResourceManager.GetString("Edit_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить лицо.
        /// </summary>
        internal static string Edit_person {
            get {
                return ResourceManager.GetString("Edit_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить название места хранения.
        /// </summary>
        internal static string Edit_place {
            get {
                return ResourceManager.GetString("Edit_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить издательство.
        /// </summary>
        internal static string Edit_pubhouse {
            get {
                return ResourceManager.GetString("Edit_pubhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить серию.
        /// </summary>
        internal static string Edit_series {
            get {
                return ResourceManager.GetString("Edit_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить действие из базы.
        /// </summary>
        internal static string Erase_Action {
            get {
                return ResourceManager.GetString("Erase_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить произведение из базы.
        /// </summary>
        internal static string Erase_Art {
            get {
                return ResourceManager.GetString("Erase_Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить запись о прочитанном произведении из базы.
        /// </summary>
        internal static string Erase_ArtRead {
            get {
                return ResourceManager.GetString("Erase_ArtRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить автора из базы.
        /// </summary>
        internal static string Erase_Author {
            get {
                return ResourceManager.GetString("Erase_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить книгу из базы.
        /// </summary>
        internal static string Erase_Book {
            get {
                return ResourceManager.GetString("Erase_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить формат прочтения из базы.
        /// </summary>
        internal static string Erase_BookFormat {
            get {
                return ResourceManager.GetString("Erase_BookFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить город из базы.
        /// </summary>
        internal static string Erase_City {
            get {
                return ResourceManager.GetString("Erase_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить жанр из базы.
        /// </summary>
        internal static string Erase_Genre {
            get {
                return ResourceManager.GetString("Erase_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить язык из базы.
        /// </summary>
        internal static string Erase_Language {
            get {
                return ResourceManager.GetString("Erase_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить оценку из базы.
        /// </summary>
        internal static string Erase_Mark {
            get {
                return ResourceManager.GetString("Erase_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить лицо из базы.
        /// </summary>
        internal static string Erase_Person {
            get {
                return ResourceManager.GetString("Erase_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить место хранения из базы.
        /// </summary>
        internal static string Erase_Place {
            get {
                return ResourceManager.GetString("Erase_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить издательство из базы.
        /// </summary>
        internal static string Erase_PublishingHouse {
            get {
                return ResourceManager.GetString("Erase_PublishingHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить рекомендацию из базы.
        /// </summary>
        internal static string Erase_Recommendation {
            get {
                return ResourceManager.GetString("Erase_Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить серию книг из базы.
        /// </summary>
        internal static string Erase_Series {
            get {
                return ResourceManager.GetString("Erase_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Безвозвратно удалить иной источник рекомендации из базы.
        /// </summary>
        internal static string Erase_SourceToreadAnother {
            get {
                return ResourceManager.GetString("Erase_SourceToreadAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RU_ini.sql.
        /// </summary>
        internal static string Filename_Init_Script {
            get {
                return ResourceManager.GetString("Filename_Init_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Формат.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Формат уже существует.
        /// </summary>
        internal static string Format_already_exists {
            get {
                return ResourceManager.GetString("Format_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список форматов прочтения.
        /// </summary>
        internal static string Formats_list {
            get {
                return ResourceManager.GetString("Formats_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Жанр.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Жанр уже существует.
        /// </summary>
        internal static string Genre_already_exists {
            get {
                return ResourceManager.GetString("Genre_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список жанров.
        /// </summary>
        internal static string Genres_list {
            get {
                return ResourceManager.GetString("Genres_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id кн..
        /// </summary>
        internal static string ID_book_short_text {
            get {
                return ResourceManager.GetString("ID_book_short_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Соединение с сервером баз данных установлено, однако, база данных не найдена.
        ///Рекомендуется создать новую базу или восстановить из бэкапа..
        /// </summary>
        internal static string Info_Connect_OK_DB_not_found {
            get {
                return ResourceManager.GetString("Info_Connect_OK_DB_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à База данных повреждена.
        ///Рекомендуется создать новую базу или восстановить из бэкапа..
        /// </summary>
        internal static string Info_DB_corrupted {
            get {
                return ResourceManager.GetString("Info_DB_corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Соединение с сервером баз данных не установлено..
        /// </summary>
        internal static string Info_DB_No_Connection {
            get {
                return ResourceManager.GetString("Info_DB_No_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à База данных не найдена.
        ///Рекомендуется создать новую базу или восстановить из бэкапа..
        /// </summary>
        internal static string Info_DB_not_found {
            get {
                return ResourceManager.GetString("Info_DB_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Язык уже существует.
        /// </summary>
        internal static string Language_already_exists {
            get {
                return ResourceManager.GetString("Language_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Язык издания.
        /// </summary>
        internal static string Language_pub {
            get {
                return ResourceManager.GetString("Language_pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список языков.
        /// </summary>
        internal static string Languages_list {
            get {
                return ResourceManager.GetString("Languages_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Язык ориг..
        /// </summary>
        internal static string Langue_original {
            get {
                return ResourceManager.GetString("Langue_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Оценка.
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Оценка уже существует.
        /// </summary>
        internal static string Mark_already_exists {
            get {
                return ResourceManager.GetString("Mark_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список оценок.
        /// </summary>
        internal static string Marks_list {
            get {
                return ResourceManager.GetString("Marks_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Сообщение.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Новое название:.
        /// </summary>
        internal static string New_appellation {
            get {
                return ResourceManager.GetString("New_appellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Новый формат:.
        /// </summary>
        internal static string New_format {
            get {
                return ResourceManager.GetString("New_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Новое имя:.
        /// </summary>
        internal static string New_name {
            get {
                return ResourceManager.GetString("New_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Примечание.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Другие рекомендуют авторов.
        /// </summary>
        internal static string Others_recommend_authors {
            get {
                return ResourceManager.GetString("Others_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Другие рекомендуют книги.
        /// </summary>
        internal static string Others_recommend_books {
            get {
                return ResourceManager.GetString("Others_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Страниц.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Пароль верный.
        /// </summary>
        internal static string Password_Correct {
            get {
                return ResourceManager.GetString("Password_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Лицо:.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Лицо уже существует.
        /// </summary>
        internal static string Person_already_exists {
            get {
                return ResourceManager.GetString("Person_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ФИО:.
        /// </summary>
        internal static string Person_short_name {
            get {
                return ResourceManager.GetString("Person_short_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список людей.
        /// </summary>
        internal static string Persons_list {
            get {
                return ResourceManager.GetString("Persons_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Место хранения уже существует.
        /// </summary>
        internal static string Place_already_exists {
            get {
                return ResourceManager.GetString("Place_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Название места хранения:.
        /// </summary>
        internal static string Place_name {
            get {
                return ResourceManager.GetString("Place_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Размещение.
        /// </summary>
        internal static string Placement {
            get {
                return ResourceManager.GetString("Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Записи размещения.
        /// </summary>
        internal static string Placements_list {
            get {
                return ResourceManager.GetString("Placements_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Издательство.
        /// </summary>
        internal static string Pubhouse {
            get {
                return ResourceManager.GetString("Pubhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Издательство уже существует.
        /// </summary>
        internal static string Pubhouse_already_exists {
            get {
                return ResourceManager.GetString("Pubhouse_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Название издательства:.
        /// </summary>
        internal static string Pubhouse_name {
            get {
                return ResourceManager.GetString("Pubhouse_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список издательств.
        /// </summary>
        internal static string Pubhouses_list {
            get {
                return ResourceManager.GetString("Pubhouses_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Год изд..
        /// </summary>
        internal static string Publication_year {
            get {
                return ResourceManager.GetString("Publication_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список прочтённого.
        /// </summary>
        internal static string Read_list {
            get {
                return ResourceManager.GetString("Read_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Рекомендация.
        /// </summary>
        internal static string Recommendation {
            get {
                return ResourceManager.GetString("Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Тип рек..
        /// </summary>
        internal static string Recommendation_type {
            get {
                return ResourceManager.GetString("Recommendation_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список рекомендаций.
        /// </summary>
        internal static string Recommendations_list {
            get {
                return ResourceManager.GetString("Recommendations_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Серия.
        /// </summary>
        internal static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Серия уже существует.
        /// </summary>
        internal static string Series_already_exist {
            get {
                return ResourceManager.GetString("Series_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список серий книг.
        /// </summary>
        internal static string Series_list {
            get {
                return ResourceManager.GetString("Series_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Имя.
        /// </summary>
        internal static string Simple_proper_name {
            get {
                return ResourceManager.GetString("Simple_proper_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Источник.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Тип ист..
        /// </summary>
        internal static string Source_type {
            get {
                return ResourceManager.GetString("Source_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Место хранения.
        /// </summary>
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Список мест хранения.
        /// </summary>
        internal static string Storages_list {
            get {
                return ResourceManager.GetString("Storages_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Значение не может быть пустым.
        /// </summary>
        internal static string Value_cannot_be__empty {
            get {
                return ResourceManager.GetString("Value_cannot_be_ empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Предупреждение.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Вы действительно хотите безвозвратно удалить базу даннаых?.
        /// </summary>
        internal static string Warning_BD_Deleting {
            get {
                return ResourceManager.GetString("Warning_BD_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Где книги.
        /// </summary>
        internal static string Where_books {
            get {
                return ResourceManager.GetString("Where_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à У кого мои книги.
        /// </summary>
        internal static string Who_has_my_books {
            get {
                return ResourceManager.GetString("Who_has_my_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Год написания.
        /// </summary>
        internal static string Writing_year {
            get {
                return ResourceManager.GetString("Writing_year", resourceCulture);
            }
        }
    }
}
