//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_postgres.CODE.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RU() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_postgres.CODE.Localization.RU", typeof(RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить другой источник рекомендации.
        /// </summary>
        internal static string Add_another_source {
            get {
                return ResourceManager.GetString("Add_another_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить автора:.
        /// </summary>
        internal static string Add_author {
            get {
                return ResourceManager.GetString("Add_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить город.
        /// </summary>
        internal static string Add_city {
            get {
                return ResourceManager.GetString("Add_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить формат.
        /// </summary>
        internal static string Add_format {
            get {
                return ResourceManager.GetString("Add_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить жанр.
        /// </summary>
        internal static string Add_genre {
            get {
                return ResourceManager.GetString("Add_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить язык.
        /// </summary>
        internal static string Add_language {
            get {
                return ResourceManager.GetString("Add_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить оценку.
        /// </summary>
        internal static string Add_mark {
            get {
                return ResourceManager.GetString("Add_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить лицо.
        /// </summary>
        internal static string Add_person {
            get {
                return ResourceManager.GetString("Add_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить место хранения.
        /// </summary>
        internal static string Add_place {
            get {
                return ResourceManager.GetString("Add_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить издательство.
        /// </summary>
        internal static string Add_pubhouse {
            get {
                return ResourceManager.GetString("Add_pubhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Добавить серию книг.
        /// </summary>
        internal static string Add_series {
            get {
                return ResourceManager.GetString("Add_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Источник уже существует.
        /// </summary>
        internal static string Another_source_already_exists {
            get {
                return ResourceManager.GetString("Another_source_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Название:.
        /// </summary>
        internal static string Appellation {
            get {
                return ResourceManager.GetString("Appellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Автор.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Автор уже существует.
        /// </summary>
        internal static string Author_alredy_exists {
            get {
                return ResourceManager.GetString("Author_alredy_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Авторы.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Авторы рекомендуют авторов.
        /// </summary>
        internal static string Authors_recommend_authors {
            get {
                return ResourceManager.GetString("Authors_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Авторы рекомендуют книги.
        /// </summary>
        internal static string Authors_recommend_books {
            get {
                return ResourceManager.GetString("Authors_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Книги.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Книги рекомендуют авторов.
        /// </summary>
        internal static string Books_recommend_authors {
            get {
                return ResourceManager.GetString("Books_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Книги рекомендуют книги.
        /// </summary>
        internal static string Books_recommend_books {
            get {
                return ResourceManager.GetString("Books_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Другое.
        /// </summary>
        internal static string caption_from_anothers {
            get {
                return ResourceManager.GetString("caption_from_anothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à От авторов.
        /// </summary>
        internal static string caption_from_authors {
            get {
                return ResourceManager.GetString("caption_from_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Из книг.
        /// </summary>
        internal static string caption_from_books {
            get {
                return ResourceManager.GetString("caption_from_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Город уже существует.
        /// </summary>
        internal static string City_already_exists {
            get {
                return ResourceManager.GetString("City_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить иной источник рекомендации.
        /// </summary>
        internal static string Edit_another_source {
            get {
                return ResourceManager.GetString("Edit_another_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить имя автора.
        /// </summary>
        internal static string Edit_author_name {
            get {
                return ResourceManager.GetString("Edit_author_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить город.
        /// </summary>
        internal static string Edit_city {
            get {
                return ResourceManager.GetString("Edit_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить формат.
        /// </summary>
        internal static string Edit_format {
            get {
                return ResourceManager.GetString("Edit_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить жанр.
        /// </summary>
        internal static string Edit_genre {
            get {
                return ResourceManager.GetString("Edit_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить язык.
        /// </summary>
        internal static string Edit_language {
            get {
                return ResourceManager.GetString("Edit_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить оценку.
        /// </summary>
        internal static string Edit_mark {
            get {
                return ResourceManager.GetString("Edit_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить лицо.
        /// </summary>
        internal static string Edit_person {
            get {
                return ResourceManager.GetString("Edit_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить название места хранения.
        /// </summary>
        internal static string Edit_place {
            get {
                return ResourceManager.GetString("Edit_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить издательство.
        /// </summary>
        internal static string Edit_pubhouse {
            get {
                return ResourceManager.GetString("Edit_pubhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Изменить серию.
        /// </summary>
        internal static string Edit_series {
            get {
                return ResourceManager.GetString("Edit_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Формат уже существует.
        /// </summary>
        internal static string Format_already_exists {
            get {
                return ResourceManager.GetString("Format_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Жанр уже существует.
        /// </summary>
        internal static string Genre_already_exists {
            get {
                return ResourceManager.GetString("Genre_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Язык уже существует.
        /// </summary>
        internal static string Language_already_exists {
            get {
                return ResourceManager.GetString("Language_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Оценка уже существует.
        /// </summary>
        internal static string Mark_already_exists {
            get {
                return ResourceManager.GetString("Mark_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Новое название:.
        /// </summary>
        internal static string New_appellation {
            get {
                return ResourceManager.GetString("New_appellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Новый формат:.
        /// </summary>
        internal static string New_format {
            get {
                return ResourceManager.GetString("New_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Новое имя:.
        /// </summary>
        internal static string New_name {
            get {
                return ResourceManager.GetString("New_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Другие рекомендуют авторов.
        /// </summary>
        internal static string Others_recommend_authors {
            get {
                return ResourceManager.GetString("Others_recommend_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Другие рекомендуют книги.
        /// </summary>
        internal static string Others_recommend_books {
            get {
                return ResourceManager.GetString("Others_recommend_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Лицо:.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Лицо уже существует.
        /// </summary>
        internal static string Person_already_exists {
            get {
                return ResourceManager.GetString("Person_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ФИО:.
        /// </summary>
        internal static string Person_short_name {
            get {
                return ResourceManager.GetString("Person_short_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Место хранения уже существует.
        /// </summary>
        internal static string Place_already_exists {
            get {
                return ResourceManager.GetString("Place_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Название места хранения:.
        /// </summary>
        internal static string Place_name {
            get {
                return ResourceManager.GetString("Place_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Издательство уже существует.
        /// </summary>
        internal static string Pubhouse_already_exists {
            get {
                return ResourceManager.GetString("Pubhouse_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Серия уже существует.
        /// </summary>
        internal static string Series_already_exist {
            get {
                return ResourceManager.GetString("Series_already_exist", resourceCulture);
            }
        }
    }
}
